// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGz-5psisNdBlye8b9kBRwTEsd60VrYW0',
    appId: '1:993520823883:web:e1a37ea714bf05d498a7ce',
    messagingSenderId: '993520823883',
    projectId: 'trackie-4ff67',
    authDomain: 'trackie-4ff67.firebaseapp.com',
    storageBucket: 'trackie-4ff67.firebasestorage.app',
    measurementId: 'G-3NEQK4KZ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtlJ67wHVwOC8eOFA_VUsmE7elZjVDiiE',
    appId: '1:993520823883:android:4a4ab346f969cede98a7ce',
    messagingSenderId: '993520823883',
    projectId: 'trackie-4ff67',
    storageBucket: 'trackie-4ff67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD82_PRc7scWKbpsgFX6kkZyijXSEq4qtA',
    appId: '1:993520823883:ios:633dccbf7ef210be98a7ce',
    messagingSenderId: '993520823883',
    projectId: 'trackie-4ff67',
    storageBucket: 'trackie-4ff67.firebasestorage.app',
    iosBundleId: 'com.example.trackieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD82_PRc7scWKbpsgFX6kkZyijXSEq4qtA',
    appId: '1:993520823883:ios:633dccbf7ef210be98a7ce',
    messagingSenderId: '993520823883',
    projectId: 'trackie-4ff67',
    storageBucket: 'trackie-4ff67.firebasestorage.app',
    iosBundleId: 'com.example.trackieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGz-5psisNdBlye8b9kBRwTEsd60VrYW0',
    appId: '1:993520823883:web:0be18c11384e748098a7ce',
    messagingSenderId: '993520823883',
    projectId: 'trackie-4ff67',
    authDomain: 'trackie-4ff67.firebaseapp.com',
    storageBucket: 'trackie-4ff67.firebasestorage.app',
    measurementId: 'G-WPG4F0VDG7',
  );
}
